export const EROSION_LIMITS = {
  simulationSpeed: { min: 0.1, max: 3, step: 0.1 },
  rain: { min: 0, max: 0.08, step: 0.001 },
  rainVariation: { min: 0, max: 1, step: 0.01 },
  rainScale: { min: 0.2, max: 5, step: 0.1 },
  rainMovement: { min: 0, max: 0.25, step: 0.005 },
  flow: { min: 0.05, max: 1, step: 0.01 },
  capacity: { min: 0.1, max: 4, step: 0.05 },
  erosionStrength: { min: 0, max: 2.5, step: 0.05 },
  scour: { min: 0, max: 1, step: 0.01 },
  deposition: { min: 0, max: 1, step: 0.01 },
  evaporation: { min: 0, max: 0.5, step: 0.005 },
  iterations: { min: 1, max: 6, step: 1 },
  oceanLevel: { min: -0.8, max: 0.35, step: 0.01 },
  waveHeight: { min: 0, max: 0.35, step: 0.005 },
  waveScale: { min: 0.1, max: 2, step: 0.05 },
  waveSpeed: { min: 0, max: 1.5, step: 0.05 },
  growthRate: { min: 0, max: 1, step: 0.01 },
  moisturePreference: { min: 0.05, max: 0.95, step: 0.01 },
  elevationRange: { min: 0.1, max: 1.5, step: 0.02 },
  slopeTolerance: { min: 0.02, max: 0.6, step: 0.01 },
  spread: { min: 0, max: 1, step: 0.01 },
  dieOffRate: { min: 0, max: 1, step: 0.01 },
  erosionResistance: { min: 0, max: 1, step: 0.01 },
}

export const DEFAULT_EROSION = {
  running: true,
  simulationSpeed: 1,
  rainVariation: 0.68,
  rainMovement: 0.035,
  showTerrain: true,
  showRain: true,
  showWater: true,
  showErosion: true,
  vegetationEnabled: true,
  showVegetation: true,
  showSoilMoisture: false,
  wireframe: false,
  rain: 0.014,
  rainScale: 1.5,
  flow: 0.62,
  capacity: 1.65,
  erosionStrength: 0.9,
  scour: 0.48,
  deposition: 0.24,
  evaporation: 0.085,
  iterations: 3,
  oceanLevel: -0.26,
  waveHeight: 0.055,
  waveScale: 0.55,
  waveSpeed: 0.32,
  growthRate: 0.32,
  moisturePreference: 0.5,
  elevationRange: 0.62,
  slopeTolerance: 0.18,
  spread: 0.7,
  dieOffRate: 0.13,
  erosionResistance: 0.78,
}

export const EROSION_TIPS = {
  running: 'Runs or pauses the environmental simulation. Recording remains independent.',
  simulationSpeed: 'Multiplier applied to fixed simulation time without changing render FPS.',
  terrain: 'Shows or hides the solid terrain surface.',
  rainView: 'Shows rain particles sampled from the same precipitation field as the solver.',
  water: 'Shows the separate inland water surface.',
  erosionView: 'Highlights cells that were recently eroded or received deposited material.',
  rain: 'Precipitation volume added to the shared water field per second.',
  rainVariation: 'Difference between wet storm cells and dry regions. Zero approaches uniform rain.',
  rainScale: 'Spatial size of rain systems. Higher values create smaller storm cells.',
  rainMovement: 'Speed at which the precipitation field drifts across the terrain.',
  flow: 'Fraction of water moved downhill per step.',
  capacity: 'Maximum sediment water can carry. Higher values cut deeper channels.',
  erosionStrength: 'High-level multiplier for terrain change from water depth, velocity, and slope.',
  scour: 'Rate at which undersaturated water removes terrain.',
  deposition: 'Rate at which excess sediment is deposited back onto terrain.',
  evaporation: 'Continuous loss from the same water field filled by rainfall.',
  iterations: 'Maximum fixed hydraulic substeps per rendered frame.',
  oceanLevel: 'Sea-level boundary condition. Lower terrain is submerged and boundary water drains here.',
  waveHeight: 'Visual displacement amplitude of the surrounding ocean.',
  waveScale: 'Wavelength density of the surrounding ocean.',
  waveSpeed: 'Animation speed of the visual ocean waves.',
  vegetationEnabled: 'Runs or pauses ecological growth while preserving current vegetation.',
  vegetationView: 'Shows dark ground coverage and instanced architectural vegetation.',
  soilMoistureView: 'Displays the slow soil-moisture field as a restrained violet ground overlay.',
  growthRate: 'Rate at which suitable cells accumulate vegetation density.',
  moisturePreference: 'Preferred soil moisture. Drier or flooded cells become less suitable.',
  elevationRange: 'Vertical range above ocean level where vegetation can survive.',
  slopeTolerance: 'Maximum local terrain steepness vegetation tolerates.',
  spread: 'Influence of healthy neighboring vegetation on colonization.',
  dieOffRate: 'Rate of vegetation loss under drought, flooding, steep slopes, or instability.',
  erosionResistance: 'Strength of vegetation protection against flow and hydraulic erosion.',
  wireframe: 'Shows the terrain mesh topology. Toggle with the W key.',
}
